spring:
  application:    name: ede-api-gateway  cloud:    gateway:      routes:      - id: ede-hystrix-dashboard
        uri: lb://ede-hystrix-dashboard        predicates:        - Path=/ede-hystrix-dashboard/**
      - id: ede-cloud-config
        uri: lb://ede-cloud-config
        predicates:
        - Path=/ede-cloud-config/**
      - id: ede-order
        uri: lb://ede-order
        predicates:
        - Path=/ede-order/**
      - id: ede-customer
        uri: lb://ede-customer
        predicates:
        - Path=/ede-customer/**
      - id: ede-product
        uri: lb://ede-product
        predicates:
        - Path=/ede-product/**
      - id: ede-system
        uri: lb://ede-system
        predicates:
        - Path=/ede-system/**
      - id: ede-oauth-service
        uri: lb://ede-oauth-service
        predicates:
        - Path=/ede-oauth-service/**
      - id: ede-oauth-service
        uri: lb://ede-file
        predicates:
        - Path=/ede-file/**
server:
  port: 8080  