spring:
   application:
      name: CONFIG-SERVER
   cloud:
      config:
         server:
            git:
               uri: https://gitlab.com/group-poly/ede.git
               clone-on-start: true
               default-label: SP0001-ST01
               username: teamsdarkeyes2021
               password: teamsdarkeyes2021
server:
   port: 8888