spring:
   application:
      name: CONFIG-SERVER
   cloud:
      config:
         server:
            git:
               uri: https://gitlab.com/group-poly/ede/-/tree/master/ede-be/config-cloud-file
               basedir: target/config
               default-label: master
server:
   port: 8888