server:
  port: 9100

spring:
  h2:
    console:
      enabled: true
  application:
    name: ede-AUTH-SERVICE
eureka:
  client:
    register-with-eureka:  true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost