spring:
   application:
      name: ede-cloud-config
   jmx:
    default_domain: cloud.config.server
   cloud:
      config:
         server:
            git:
               uri: https://gitlab.com/group-poly/ede.git
               skipSslValidation: true
               username: teamsdarkeyes2021
               password: teamsdarkeyes2021
               default-label: SP0002-ST01
               search-paths: /ede-be/config-cloud-file 
management:
   endpoints:
      web:
         exposure:
            include: /*
server:
   port: 8888